#+TITLE: 2020最大惊喜？
#+AUTHOR: rx-78-kum0
#+DATE: 2020-07-27
#+DESCRIPTION: 2020最大的惊喜？大概率是了
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: 记录
#+HUGO_CATEGORIES: balabala
#+HUGO_DRAFT: nil
#+HUGO_BASE_DIR: ~/WWW-BUILDER
#+HUGO_SECTION: posts


* 正是在下
#+BEGIN_VERSE
从订车到现在两周，现在还对此没有实感...
#+END_VERSE

#+BEGIN_VERSE
这次从第一次到4s闲逛到订车再到提车最后上牌，全程由我和老婆两人着手。算是从头到尾彻彻底底体验了一次购车。
对汽车这个行业是一块多么巨大的蛋糕有了初步的了解。二手车(之前的丰田小车开了快三年居然只亏了2w多，不得不说阿丰真的很保值)、主机厂、4s店、汽贸、维修、保养、保险、甚至租赁，每个环节单独拎出来都是一个庞大的产业。
也意识到国家10年前就高瞻远瞩布局新能源是多么明智。

新能源基金加仓🐶
#+END_VERSE

** 选择A4L的理由
#+BEGIN_QUOTE
其实很久以前的dream car就是雷克萨斯ct200h。
最爱两厢小车。

但多少年过去了ct200h还不换代，配置已经跟不上时代的步伐了。
#+END_QUOTE

#+BEGIN_VERSE
最开始看了X2和3系。
x2配置太不厚道了(三缸接受不能，家里的x1三缸抖得厉害)。
325i是真的好看，标轴大小合适，但标轴没有全景天窗。(主要还是贵..)

别摸我的风格就像是一座豪华酒店，不太喜欢也hold不住。
#+END_VERSE

#+BEGIN_VERSE
然后看了A3和Q3。
A3没有液晶仪表盘，而且2021换代的A3很酷但得等明年了，现在入手就是49年入国军。
第一次看完Q3就基本已经确定了，虽然不是很喜欢suv，但适合家用，而且科技氛围很赞(科技感有些过了，毕竟车不是电子产品，见仁见智)，40tfsi的配置也很足，不过档杆造型是硬伤。

但计算(杀价)40tfsi的Q3的价格有些超过了我对Q3的价值定位。最后4s门口试驾的灰色(天云灰)A4L吸引了我(4s大厅全停白色的A4L似乎不太明智，白色很容易忽略)。
毕竟Q3/A3是一台MQB平台(发动机横置)的车，而A4L是MLB平台(发动机纵置)。虽然MQB的上限有灯厂TT，可MLB的上限是兰博基尼Urus啊(好像开上了兰博)。MQB作为发动机横置平台，前悬挂空间有限只能上麦弗逊，显然MLB的多连杆独立悬挂更胜一筹。
虽然尺寸大了点，但新款造型较老款更运动利落，视觉效果显小。 
不过A4的配置也是很鸡贼...

灯厂更像是日剧中的写字楼，灰白相间简单利落，很理工科也可以很运动。(当然A6A8就很商务了)
#+END_VERSE

#+BEGIN_VERSE
这次购车唯一的遗憾可能是还差一点儿就能上灯厂引以为傲的Quattro四驱吧。

除了贵以外，还有也是Q3 -> A4L的理由(主要还是贵..)。Quattro版本超出了我心目中A4L的价值定位，因为可以上A4 Avant了。
#+END_VERSE
